exec swayidle -w \
    timeout 300 'fancylocksway' \
    timeout 600 'swaymsg "output * power off"' \
    timeout 1800 'systemctl suspend-then-hibernate' \
    resume 'swaymsg "output * power on"' \
    before-sleep 'fancylocksway' \
    lock 'fancylocksway'
