exec swayidle -w \
    timeout 300 'fancylocksway' \
    timeout 600 'swaymsg "output * power off"' \
        resume 'swaymsg "output * power on"' \
    after-resume 'sleep 2; swaymsg "output * power on"' \
    before-sleep 'fancylocksway' \
    lock 'fancylocksway'
