[default]
# Matches mako config-light / waybar style-light.
background = rgba(235, 235, 219, 0.90)
border-color = rgba(192, 223, 111, 0.90)
bar-fg-color = rgba(44, 62, 80, 0.90)
bar-bg-color = rgba(152, 209, 206, 0.90)
