[default]
# Matches mako config-dark / waybar style-dark.
background = rgba(10, 15, 20, 0.90)
border-color = rgba(8, 102, 8, 0.90)
bar-fg-color = rgba(236, 240, 241, 0.90)
bar-bg-color = rgba(44, 62, 80, 0.90)
