#!/usr/bin/env sh
#
# wm independent hotkeys
#
#

# show keybindings
super + shift + r
  sxhkd-show-bindings

# kill an application
super + shift + BackSpace
  exec xkill

# terminal emulator
super + Return
  ldpi alacritty

# alternate terminal emulator
super + shift + Return
  emacsclient -nc

# vifm file manager
super + alt + Return
  alacritty -e vifmrun

# dolphin
super + d
  dolphin

# edit whatever in emacs
super + z
  emacsclient --eval "(emacs-everywhere)"

# org-capture
super + c
  emacs-capture --eval '(bergheim/capture)'

super + t
  emacs-clock-in

# make sxhkd reload its configuration files:
super + F6
  pkill -USR1 -x sxhkd

# screenshot
super + @F1
  screenshot && notify-send -u low 'Screenshot captured'

# screenshot area
super + @F2
  screenshot -a && notify-send -u low 'Screenshot area captured'

# toggle desktop dark/white
super + F7
  toggle-darkmode

# toggle redshift
super + F8
  (pkill redshift && dunstify "Disabling redhsift" --icon=to-the-moon) || (dunstify "Enabling redshift" --icon=to-the-moon && redshift)

super + F9
  (pkill picom && dunstify "Disabling picom" --icon=to-the-moon) || (dunstify "Enabling picom" --icon=to-the-moon && picom)

super + y
   pulseaudio-control --node-type output --node-blacklist "alsa_output.pci-0000_02_00.1.hdmi-stereo,alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.mono-chat" next-node

# lock screen
super + F12
  exec fancylocki3

# toggle autolock
super + shift + F12
  exec desktop-locker toggle

# run command
super + r
  rofi -show combi -combi-modi "drun,run" -modi "combi,calc,emoji,unifont:rofimoji,Power Menu:rofi-power-menu"

super + shift + e
  rofi -modes "emoji" -show emoji -display-window "Insert emoji:"

# switch window
alt + Tab
  rofi -show window -display-window "Switch to window: "

# enter password
super + p
  rofi-pass

# clipboard manager
super + v
  CM_LAUNCHER=rofi clipmenu

{XF86AudioPrev, XF86AudioNext, XF86AudioPlay}
  playerctl {previous, next, play-pause}

# toggle audio mute
XF86AudioMute
  pactl set-sink-mute @DEFAULT_SINK@ toggle

{XF86AudioLowerVolume, XF86AudioRaiseVolume}
  pactl set-sink-volume @DEFAULT_SINK@ {-5%, +5%}

# close notification
super + ctrl + grave
  dunstctl close

# restore notification
super + ctrl + 1
  dunstctl history-pop

super + ctrl + 3
  dunstctl close-all

# act on notification
super + ctrl + 2
  dunstctl context
