#!/usr/bin/env sh
#
# wm independent hotkeys

# show keybindings
super + shift + r
  sxhkd-show-bindings

# kill an application
super + shift + BackSpace
  exec xkill

# emacsclient
super + Return
  emacsclient -nc

# terminal emulator
super + shift + Return
  ldpi alacritty

# vifm file manager
super + ctrl + Return
  alacritty -e vifmrun

# dolphin file manager
super + d
  dolphin

# emacs: edit whatever
super + z
  emacsclient --eval "(emacs-everywhere)"

# emacs: org-capture
super + c
  emacs-capture --eval '(bergheim/capture)'

# emacs: clock in to task
super + t
  emacs-clock-in

# make sxhkd reload its configuration files:
super + F6
  pkill -USR1 -x sxhkd

# screenshot
super + @F1
  screenshot && notify-send -u low 'Screenshot captured'

# screenshot area
super + @F2
  screenshot -a && notify-send -u low 'Screenshot area captured'

# toggle desktop dark/white
super + F7
  toggle-darkmode

# toggle redshift
super + F8
  (pkill redshift && dunstify "Disabling redhsift" --icon=to-the-moon) || (dunstify "Enabling redshift" --icon=to-the-moon && redshift)

# toggle picom / hardware acceleration
super + F9
  (pkill picom && dunstify "Disabling picom" --icon=to-the-moon) || (dunstify "Enabling picom" --icon=to-the-moon && picom)

# toggle output
super + F11
    pulseaudio-control --node-type output --node-blacklist "*hdmi*","*chat*" next-node

# lock screen
super + F12
  exec fancylocki3

# toggle autolock
super + shift + F12
  exec desktop-locker toggle

# run command
super + r
  rofi -show combi -combi-modi "drun,run" -modi "combi,calc,emoji,unifont:rofimoji,Power Menu:rofi-power-menu"

# pick emoji
super + shift + e
  rofi -modes "emoji" -show emoji -display-window "Insert emoji:"

super + y
  rofi -modes "emoji" -show emoji -display-window "Insert emoji:"

# switch window
alt + Tab
  rofi -show window -display-window "Switch to window: "

# enter password
super + p
  rofi-pass

# clipboard manager
super + v
  CM_LAUNCHER=rofi clipmenu

{XF86AudioPrev, XF86AudioNext, XF86AudioPlay}
  playerctl {previous, next, play-pause}

# toggle audio mute
XF86AudioMute
  pactl set-sink-mute @DEFAULT_SINK@ toggle

{XF86AudioLowerVolume, XF86AudioRaiseVolume}
  pactl set-sink-volume @DEFAULT_SINK@ {-5%, +5%}

# dunst: close notification
super + ctrl + grave
  dunstctl close

# dunst: restore notification
super + ctrl + 1
  dunstctl history-pop

# dunst: close all notifications
super + ctrl + 3
  dunstctl close-all

# dunst: act on notification
super + ctrl + 2
  dunstctl context
