#! /bin/sh

bspc monitor DP-0 -d "" "" "" "" "" "" ""
bspc monitor HDMI-0 -d "" "" "" ""

bspc config border_width         2
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Border colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#B89000"
bspc config urgent_border_color "#B58900"
bspc config presel_feedback_color "#FFED01"

# client.focused          #D89000 #F7A500 #444444 #FFED01   #B89000

# this fixes .. apps that don't honor the spec
bspc config ignore_ewmh_focus true

# nuke the previous rules so reloading the config works as intended
bspc rule -r "*"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefoxdeveloperedition:Navigator desktop='^1' state=tiled focused=on
bspc rule -a TelegramDesktop desktop='^2' state=tiled focused=on
bspc rule -a Spotify desktop='^3' state=tiled focused=on
bspc rule -a spotify desktop='^3' state=tiled focused=on
bspc rule -a "" desktop='^3' state=tiled focused=on
bspc rule -a Chromium desktop='^4'
bspc rule -a Emacs state=tiled focused=on
bspc rule -a File-roller state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off

bspc rule -a "*:floating" state=floating
bspc rule -a scratchpad sticky=on state=floating hidden=on follow=on

# spotify hack
bspc config external_rules_command ~/.config/bspwm/rules

bspwm-scratchterm-toggle &
feh --bg-fill ~/Pictures/wallpapers/active_primary.png --bg-fill ~/Pictures/wallpapers/active_secondary.png
$HOME/.config/polybar/launch.sh
