#! /bin/sh

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d "inet  " "com  " "music  " "email  " "work  " "misc  " VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Border colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#B89000"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#FFED01"

# client.focused          #D89000 #F7A500 #444444 #FFED01   #B89000

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-scale ~/Pictures/wallpapers/active.png
