general.import = ["/home/tsb/.config/alacritty/alacritty.toml"]

[font]
size = 16.0

[font.bold]
family = "Ubuntu Mono Nerd Font"
style = "SemiBold"

[font.italic]
family = "Ubuntu Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Ubuntu Mono Nerd Font"
style = "Regular"

# [colors.bright]
# black   = "0x686868"
# red     = "0xF07178"
# green   = "0xC2D94C"
# yellow  = "0xFFB454"
# blue    = "0x59C2FF"
# magenta = "0xFFEE99"
# cyan    = "0x95E6CB"
# white   = "0xFFFFFF"

# [colors.normal]
# black   = "0x01060E"
# red     = "0xEA6C73"
# green   = "0x91B362"
# yellow  = "0xF9AF4F"
# blue    = "0x53BDFA"
# magenta = "0xFAE994"
# cyan    = "0x90E1C6"
# white   = "0xC7C7C7"

# [colors.primary]
# background = "0x141414"
# foreground = "0xB3B1AD"

# [window]
# opacity = 0.8
