#!/bin/bash

sudo pacman -S $(grep -o '^[^#]*' ~/.config/bootstrap/archlinux/packages.pacman)

# TODO: install an AUR manager
# sudo pacaur/yay/whatever -S $(grep -o '^[^#]*' ~/.config/bootstrap/archlinux/packages.aur)
